-- Cleanup API test data generated by scripts/api-tests.

DELETE FROM cash_transactions WHERE user_id = 900001;
DELETE FROM trade_history
WHERE holding_id IN (
    SELECT id
    FROM holdings
    WHERE user_id = 900001
);
DELETE FROM watchlist WHERE user_id = 900001 AND asset_id = 900101;
DELETE FROM holdings WHERE user_id = 900001 AND asset_id = 900101;
DELETE FROM cash_accounts WHERE user_id = 900001 AND currency = 'USD';
DELETE FROM asset_price_daily WHERE asset_id = 900101;
DELETE FROM asset_stock_detail WHERE asset_id = 900101;
DELETE FROM assets WHERE id = 900101;
DELETE FROM users WHERE id = 900001;
