spring:
  datasource:
    url: jdbc:h2:mem:portfolio_management;MODE=MySQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  sql:
    init:
      mode: always
      schema-locations: classpath:schema-local.sql
resilience:
  rate-limit:
    enabled: false
scheduler:
  jobs:
    market-data-refresh:
      enabled: false
    fx-rate-refresh:
      enabled: false
    portfolio-nav-snapshot:
      enabled: false
    system-config-refresh:
      enabled: false
yahoo-finance:
  enabled: false
finnhub:
  enabled: true
  base-url: ${FINNHUB_BASE_URL:https://finnhub.io}
  timeout: ${FINNHUB_TIMEOUT:5s}
  api-key: ${FINNHUB_API_KEY:d75nub1r01qk56kdf63gd75nub1r01qk56kdf640}
twelve-data:
  enabled: true
  base-url: ${TWELVE_DATA_BASE_URL:https://api.twelvedata.com}
  timeout: ${TWELVE_DATA_TIMEOUT:5s}
  api-key: ${TWELVE_DATA_API_KEY:c993f88aa55f41418fc3449756880e99}
eastmoney:
  enabled: true
  base-url: ${EASTMONEY_BASE_URL:https://push2his.eastmoney.com}
  timeout: ${EASTMONEY_TIMEOUT:5s}
